"""add code to recharge

Revision ID: 9e0c584873ea
Revises: 
Create Date: 2022-04-15 14:51:53.714471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0c584873ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recharge', sa.Column('code', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'recharge', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recharge', type_='unique')
    op.drop_column('recharge', 'code')
    # ### end Alembic commands ###
